# Your name and what you do
name: Nikshep Svn
bio: Software Engineer

description: Nikshep Svn's Home on the Interwebs

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://nikshepsvn.github.io/Eve/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: mytwitter
linkedin: nikshepsvn
github: nikshepsvn
email: nikshepsvn@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# do you want to display an about section? true or false
about: true

# do you want to display a projects section? true or false
projects: true

work: true

# add your projects here
project-list:
    ScatterFly:
        name: ScatterFly
        description: An attempt to improve user privacy by intelligent data obfuscation.
        url: https://github.com/nikshepsvn/ScatterFly
    Giftory:
        name: Giftory
        description: Convert any piece of text into an entertaining GIF movie!
        url: https://github.com/nikshepsvn/Giftory
    TumbleWeed:
        name: TumbleWeed
        description: Lead generation platform that let's you aquire leads from LinkedIn based on multiple criteria.
        url: https://github.com/nikshepsvn/TumbleWeed

work-list:
    PagerDuty2:
        name: PagerDuty (Data Science Intern)
        description: Will be working on enabling Machine Learning at Scale by supporting more efficient sourcing and processing of event and incident data.
        url: https://www.pagerduty.com/features/event-intelligence-and-automation/
    PagerDuty1:
        name: PagerDuty (Core Infrastructure Intern)
        description: Worked on improving PagerDuty's internal infrastructure by developing replacement service that shipped records from SQL to Kafka that significantly reduced DB locking and load.
        url: https://www.pagerduty.com
    Magmic:
        name: Magmic (Backend Engineering Intern)
        description: Worked on the main game server and a new faster authentication flow while improving the services resiliency agaisnt attacks and threats.
        url: https://magmic.com


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
